### PR TITLE
add: Inference Notebook

### PR DESCRIPTION
**Pull request by SohaibAnwaar**
Add
1. Added the inference notebook for custom images.

### CODE REVIEW

**Comment by SohaibAnwaar** [comment]
Notebook Code: https://github.com/SohaibAnwaar/MonoScene/blob/add/JupyterNotebook/jupyter_notebooks/predict_custom.ipynb


Notebook Output:
screenshot_28

**Comment by SohaibAnwaar** [comment]
@anhquancao I made a notebook for custom Image prediction. Can you please merge it 🤝

**Comment by anhquancao** [comment]
Hi! Thank you for putting in the effort to write these codes! However, I'm afraid I won't be able to check them or maintain them in the future due to time constraints. Could please put these codes in a new repository or create a Hugging Face demo instead? That way, I can still mention them in the Readme file and give them the attention they deserve. Thanks a lot!

**Comment by SohaibAnwaar** [comment]
Sure let me make a new Repo for it 👍🏼

**Comment by anhquancao** [comment]
Great! Thank you

**Pull request closed without merging**
